account/urls.py
from django.conf.urls import patterns, url
from account.views import Login, Logout, GetCurrentUserView, SetTimezone, GetUsersView, PhoneCodeGenerating, \
    Registration, RegistrationUpdate, GetServiceTips, GetCurrencies, UploadImageToVK, AvatarUpdateView, \
    MainInfoUpdateView, AddressUpdateView, ProfessionalInfoUpdateView, DiplomCreateView, LicenseCreateView, \
    DiplomDeleteView, LicenseDeleteView, AssociationCreateView, AssociationDeleteView, NotificationsUpdateView, \
    ServiceCreateView, ServiceDeleteView, UploadImageToFB, PhoneUpdateView, ResumeDeleteView, ConnectVKAuth, \
    ConnectFBAuth, CheckRegistration, LawBranchCreateView, LawBranchDeleteView, LawInstituteCreateView, \
    LawInstituteDeleteView

urlpatterns = patterns('',
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^login/status/$', Login.as_view(), name='login_status'),
    url(r'^logout/$', Logout.as_view(), name='logout'),
    url(r'^data/$', GetCurrentUserView.as_view(), name='get_current_user'),
    url(r'^tz/$', SetTimezone.as_view(), name='set_timezone'),
    url(r'^users/$', GetUsersView.as_view(), name='get_users'),
    url(r'^services/$', GetServiceTips.as_view(), name='get_services'),
    url(r'^currencies/$', GetCurrencies.as_view(), name='get_currencies'),

    url(r'generate_phone_code/$', PhoneCodeGenerating.as_view(), name='generate_phone_code'),
    url(r'registration/$', Registration.as_view(), name='registration'),
    url(r'registration/check/$', CheckRegistration.as_view(), name='registration_check'),
    url(r'registration/(?P<token>\w+)/$', RegistrationUpdate.as_view(), name='registration_update'),
    url(r'upload_image_vk/$', UploadImageToVK.as_view(), name='upload_image_vk'),
    url(r'upload_image_fb/$', UploadImageToFB.as_view(), name='upload_image_fb'),
)

urlpatterns += patterns('',
    url(r'^cabinet/avatar/', AvatarUpdateView.as_view(), name='cabinet_avatar'),
    url(r'^cabinet/main_info/', MainInfoUpdateView.as_view(), name='cabinet_main_info'),
    url(r'^cabinet/address/', AddressUpdateView.as_view(), name='cabinet_address'),
    url(r'^cabinet/professional_info/', ProfessionalInfoUpdateView.as_view(), name='cabinet_professional_info'),
    url(r'^cabinet/diplom/add/', DiplomCreateView.as_view(), name='cabinet_diplom_add'),
    url(r'^cabinet/diplom/delete/(?P<pk>\d+)/', DiplomDeleteView.as_view(), name='cabinet_diplom_delete'),
    url(r'^cabinet/license/add/', LicenseCreateView.as_view(), name='cabinet_license_add'),
    url(r'^cabinet/license/delete/(?P<pk>\d+)/', LicenseDeleteView.as_view(), name='cabinet_license_delete'),
    url(r'^cabinet/association/add/', AssociationCreateView.as_view(), name='cabinet_association_add'),
    url(r'^cabinet/association/delete/(?P<pk>\d+)/', AssociationDeleteView.as_view(), name='cabinet_association_delete'),
    url(r'^cabinet/service/add/', ServiceCreateView.as_view(), name='cabinet_service_add'),
    url(r'^cabinet/service/delete/(?P<pk>\d+)/', ServiceDeleteView.as_view(), name='cabinet_service_delete'),

    url(r'^cabinet/lawbranch/add/', LawBranchCreateView.as_view(), name='cabinet_lawbranch_add'),
    url(r'^cabinet/lawbranch/delete/(?P<pk>\d+)/', LawBranchDeleteView.as_view(), name='cabinet_lawbranch_delete'),

    url(r'^cabinet/lawinstitute/add/', LawInstituteCreateView.as_view(), name='cabinet_lawinstitute_add'),
    url(r'^cabinet/lawinstitute/delete/(?P<pk>\d+)/', LawInstituteDeleteView.as_view(), name='cabinet_lawinstitute_delete'),


    url(r'^cabinet/notifications/', NotificationsUpdateView.as_view(), name='cabinet_notifications'),
    url(r'^cabinet/resume/delete/', ResumeDeleteView.as_view(), name='cabinet_resume_delete'),
)

urlpatterns += patterns('',
    url(r'^cabinet/phone/', PhoneUpdateView.as_view(), name='cabinet_phone'),
    url(r'^cabinet/vk/', ConnectVKAuth.as_view(), name='cabinet_auth_connect_vk'),
    url(r'^cabinet/fb/', ConnectFBAuth.as_view(), name='cabinet_auth_connect_fb'),
)

chat/urls.py
from django.conf.urls import patterns, url
from chat.views import GetAttachmentUrlView, DeleteAttachmentView, GetChatData, ChatView, UploadAttachment, \
    CreateChatView, UpdateChatView, SearchMessages, SendMessage


urlpatterns = patterns('',
    url(r'^$', ChatView.as_view(), name='get_chat_data'),
    url(r'^create/$', CreateChatView.as_view(), name='create_chat'),
    url(r'^update/(?P<uid>[\w\-]+)/$', UpdateChatView.as_view(), name='update_chat'),
    url(r'^data/$', GetChatData.as_view(), name='get_chat_data'),
    url(r'^search/$', SearchMessages.as_view(), name='search_messages'),
    url(r'^attachment/upload/', UploadAttachment.as_view(), name='upload_attachment'),
    url(r'^attachment/delete/(?P<uid>[\w\-]+)/$', DeleteAttachmentView.as_view(), name='delete_attachment'),
    url(r'^attachment/(?P<uid>[\w\-]+)/$', GetAttachmentUrlView.as_view(), name='attachment'),
)

urlpatterns += patterns('',
    url(r'^send/$', SendMessage.as_view(), name='send_message'),
)

landing/urls.py
from django.conf.urls import patterns, url
from landing.models import ClientIntention
from landing.views import ClientIntentionView, LawyerIntentionView, LandingView, ResumeView

urlpatterns = patterns('',
    url(r'^$', LandingView.as_view(), name='root'),
    url(r'^resume/(?P<token>[\w\-]+)/$', ResumeView.as_view(), name='resume'),
    url(r'^cl/', ClientIntentionView.as_view(), name='client_intention'),
    url(r'^lw/', LawyerIntentionView.as_view(), name='lawyer_intention'),
)

lawandgauge/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from faq.views import FaqView
from landing.views import LandingView
from landing_builder.views import LandingBuilderView, LandingRegistration
from lawandgauge.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [

    # url(r'^$', IndexView.as_view(), name='index'),
    url(r'^$', LandingView.as_view(), name='index'),
    url(r'^chat/', include('chat.urls', namespace='chat', app_name='chat')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^landing/', include('landing.urls', namespace='landing', app_name='landing')),
    url(r'^map/', include('map.urls', namespace='map', app_name='map')),
    url(r'^localization/', include('localization.urls', namespace='localization', app_name='localization')),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)



urlpatterns += [
    url(r'^about/', TemplateView.as_view(template_name='landing/about.html'), name='about'),
    url(r'^ru/about/', TemplateView.as_view(template_name='landing/about_ru.html'), name='about'),
    url(r'^en/about/', TemplateView.as_view(template_name='landing/about_en.html'), name='about'),
    url(r'^our_lawyers/', TemplateView.as_view(template_name='landing/our_lawyers.html'), name='our_lawyers'),
    url(r'^mission/', TemplateView.as_view(template_name='landing/mission.html'), name='mission'),
    url(r'^privacy_policy/', TemplateView.as_view(template_name='landing/privacy_policy.html'), name='privacy'),
    url(r'^angular/views/chat/', TemplateView.as_view(template_name='views/chat.html')),
    url(r'^angular/views/profile/', TemplateView.as_view(template_name='views/profile.html')),
    url(r'^angular/views/login/', TemplateView.as_view(template_name='views/login.html')),
    url(r'^angular/views/landing/', TemplateView.as_view(template_name='views/landing.html')),
    url(r'^angular/templates/header', TemplateView.as_view(template_name='templates/header.html')),
    url(r'^angular/templates/sidebar/', TemplateView.as_view(template_name='templates/sidebar.html')),
]

landing_builder_patterns = [
    url(r'^lb/job_request/$', LandingRegistration.as_view(), name='job_request'),
    url(r'^(?P<slug>[\w\-]+)/$', LandingBuilderView.as_view(), name='landing_builder')
]

urlpatterns += i18n_patterns(
    url(r'^faq/$', FaqView.as_view(), name='faq'),
    url(r'^', include(landing_builder_patterns)),
)

map/urls.py
from django.conf.urls import patterns, url
from map.views import SearchCountry, SearchCity, GetCountries, GetCities, GetMapData

urlpatterns = patterns('',
    url(r'^countries/', GetCountries.as_view(), name='countries'),
    url(r'^cities/', GetCities.as_view(), name='cities'),
    url(r'^search/country/', SearchCountry.as_view(), name='search_country'),
    url(r'^search/city/', SearchCity.as_view(), name='search_city'),
    url(r'^data/', GetMapData.as_view(), name='data'),
)

chat/forms.py
from django import forms
from chat.models import Message, Attachment, Chat


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = Attachment
        fields = ['file']


class SendMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('sender', 'date', 'active')


class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ['title', 'participans']

chat/views.py
import brukva
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt
from django.views.generic import FormView, TemplateView, View, ListView, DetailView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
import redis
from chat.forms import UploadFileForm, ChatForm
from chat.models import Chat, Message, Attachment
from chat.utils import format_date
from lawandgauge.mixins import JsonResponseMixin, LoginRequiredJsonMixin, LoginRequiredMixin, \
    RequiredPermissionsJsonMixin
from lawandgauge.settings import SOCKJS_URL


class ChatView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(ChatView, self).get_context_data(**kwargs)
        context['sockjs_url'] = SOCKJS_URL
        return context

    @method_decorator(ensure_csrf_cookie)
    def dispatch(self, request, *args, **kwargs):
        return super(ChatView, self).dispatch(request, *args, **kwargs)


class GetChatData(JsonResponseMixin, LoginRequiredJsonMixin, View):
    """
    Getting extended data for all user chats
    """
    def get(self, request):
        r = redis.StrictRedis()
        #TODO test below stuff
        # chats = self.request.user.user_chats.filter(active=True, participans__active=True)
        if request.user.is_admin():
            chats = Chat.objects.filter(active=True)
        else:
            chats = self.request.user.user_chats.filter(active=True)
        if not chats:
            return self.json_success(data=[])
        else:
            return self.json_success(data=[{
                "id": str(chat.uid),
                "title": chat.get_title(request.user),
                "is_default": chat.default,
                "last_message": chat.get_last_message().text if chat.get_last_message() else "",
                "members": {p.pk: p.as_dict() for p in chat.participans.all()},
                "messages": [m.as_dict(tz=request.user.tz) for m in chat.chat_messages.filter(active=True)],
                "newMessageCount": r.get('unread_{}_{}'.format(request.user.pk, str(chat.uid))) or 0,
            } for chat in chats])


class UploadAttachment(JsonResponseMixin, LoginRequiredJsonMixin, FormView):
    """
    Upload attachment
    """
    form_class = UploadFileForm

    def form_valid(self, form):
        object = form.save()
        return self.json_success(msg=_('File have been uploaded'), attachment=str(object.uid), delete_url=reverse('chat:delete_attachment', kwargs={'uid': str(object.uid)}))

    def form_invalid(self, form):
        return self.json_fail(error=form.errors)


class GetAttachmentUrlView(LoginRequiredMixin, DetailView):
    """
    Getting downloadable url for attachment
    """
    model = Attachment
    slug_field = 'uid'
    slug_url_kwarg = 'uid'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.object.message.chat.participans.filter(pk=request.user.pk).exists():
            raise PermissionDenied
        if request.GET.get('download', None):
            response = HttpResponse(self.object.file, content_type='application/octet-stream')
            response['Content-Disposition'] = u'attachment; filename="%s"' % self.object.get_name()
            return response
        else:
            return HttpResponseRedirect(self.object.file.url)


class DeleteAttachmentView(JsonResponseMixin, LoginRequiredJsonMixin, DeleteView):
    """
    Deleting attachment
    """
    model = Attachment
    slug_field = 'uid'
    slug_url_kwarg = 'uid'

    def get(self, request, *args, **kwargs):
        return self.json_fail(error=_('Method not allowed'))

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.object.message.chat.participans.filter(pk=request.user.pk).exists():
            return self.json_fail(error=_('Access denied'))
        self.object.delete()
        return self.json_success(msg=_('Attachment have been deleted'))


class CreateChatView(JsonResponseMixin, LoginRequiredJsonMixin, RequiredPermissionsJsonMixin, CreateView):
    """
    Creating chat
    """
    model = Chat
    form_class = ChatForm
    required_permissions = ['chat.add_chat']

    def form_valid(self, form):
        chat = form.save()
        return self.json_success(msg=_('Chat has been created'), chat=str(chat.uid))

    def form_invalid(self, form):
        return self.json_fail(error=form.errors)


class UpdateChatView(JsonResponseMixin, LoginRequiredJsonMixin, RequiredPermissionsJsonMixin, UpdateView):
    """
    Changing chat data (title or participants)
    """
    model = Chat
    form_class = ChatForm
    slug_field = 'uid'
    slug_url_kwarg = 'uid'
    required_permissions = ['chat.change_chat']

    def form_valid(self, form):
        participans = form.cleaned_data['participans']
        if not participans:
            self.object = self.get_object()
            self.object.delete()
            return self.json_success(msg=_('Chat has been deleted'))
        else:
            self.object = form.save()
            self.object.participans.clear()
            self.object.participans.add(*[p.pk for p in participans])
            return self.json_success(msg=_('Chat has been updated'))

    def form_invalid(self, form):
        return self.json_fail(error=form.errors)


class SearchMessages(JsonResponseMixin, LoginRequiredJsonMixin, View):
    """
    Searching messages for all user chats
    """
    model = Message

    def get(self, request):
        query = request.GET.get('query')
        if query:
            qs = self.model.objects.filter(
                chat__in=self.request.user.user_chats.filter(active=True),
                text__icontains=query.strip()
            )
            messages = [m.as_dict() for m in qs]
            return self.json_success(data=messages)
        else:
            return self.json_fail(error=_('Query is empty'))


class SendMessage(JsonResponseMixin, View):
    """IN PROGRESS"""
    def post(self, request):
        client = brukva.Client()
        client.connect()
        message = request.POST.get('message')
        chat = request.POST.get('chat')
        if not chat:
            chats = [str(c.uid) for c in Chat.objects.filter(active=True)]
            for chat in chats:
                client.publish(chat, message)
        else:
            client.publish(chat, message)

        return self.json_success(msg=_('Messages sent'))

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(SendMessage, self).dispatch(request, *args, **kwargs)

templates/old/base.html
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    {% block extra_static %}{% endblock %}
</head>
<body>
    {% block content %}
        __CONTENT__
    {% endblock %}
    {% block extra_js %}

    {% endblock %}
    <script type="application/javascript">
        // using jQuery
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');

        function limitExecByInterval(fn, time) {
            var lock, execOnUnlock, args;
            return function() {
                args = arguments;
                if (!lock) {
                    lock = true;
                    var scope = this;
                    setTimeout(function() {
                        lock = false;
                        if (execOnUnlock) {
                            args.callee.apply(scope, args);
                            execOnUnlock = false;
                        }
                    }, time);
                    return fn.apply(this, args);
                } else
                    execOnUnlock = true;
            }
        }
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(HEAD|OPTIONS|TRACE)$/.test(method));
        }
        function ajaxSetupHandler(){
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    }
                }
            });
        }
        ajaxSetupHandler();
    </script>
</body>
</html>

templates/old/chat.html
{% extends 'base.html' %}

{% load i18n %}

{% block extra_static %}
    <script src="//cdn.jsdelivr.net/sockjs/0.3.4/sockjs.min.js"></script>
    <style>
        .hide { display: none; }
    </style>
{% endblock %}

{% block content %}
    <h1>Чат</h1>
    <table border="">
        <tr>
            <td valign="top" width="20%">
                <h2>Список чатов</h2>
                {% for chat in chats %}
                    <div>
                        <a class="chat_selector" href="#" data-uid="{{ chat.uid }}"><strong>{{ chat.title }}</strong><span class="count"></span></a><br/>
                        <span data-uid="{{ chat.uid }}" class="last_message">
                            {{ chat.get_last_message.text }}
                        </span>

                    </div>
                {% endfor %}
            </td>
                <td width="80%">
                {% for chat in chats %}
                    <div class="chat_window hide" data-uid="{{ chat.uid }}">
                        <div class="message_area"></div>
                        <form action="." method="post">{% csrf_token %}
                            <textarea name="message" id="" cols="30" rows="10" placeholder="{% trans 'Input message' %}"></textarea>
                            <br/>
                            <input type="submit" value="{% trans 'Send' %}"/>
                        </form>
                    </div>
                {% endfor %}
                </td>
        </tr>
    </table>

{% endblock %}

{% block extra_js %}
    <script type="application/javascript">

        //login
        $.post('/account/login/', {username: "test", password:"123"}, function(r){console.log(r)});

        //logout
        $.post('/account/logout/', function(r){console.log(r)});

        // get current user data
        $.get('/account/data/', function(r){
            console.log('current_user', r);
        });

        // get chat data
        var chat_data;
        $.get('/chat/data/', function(r){
            console.log(r);
            if (r.success){
                chat_data = r.data;
                // build chat list here
            }
        });

        var SOCKJS_URL = '{{ sockjs_url }}';

        var sock = new SockJS(SOCKJS_URL);

        sock.onconnect = function() {};

        sock.onopen = function () {
            console.log('open');
        };

        sock.onmessage = function (message) {
            // message come from server
            console.log('message', message);
            if (message.type == 'message') {
                if (message.data.type == 10){
                    console.log('Notification', message.data)
                } else if (message.data.type == 20) {
                    console.log('Update', message.data)
                    $.each(message.data.data, function(index, item){
                        $('a[data-uid=' + item.chat + '] span.count').html(item.unread);
                        $('span[data-uid='+item.chat+']').html(item.last_message);
                    })
                } else {
                    var uid = message.data.chat;
                    $('.chat_window[data-uid='+uid+'] .message_area').append(('<p><strong>' + message.data.sender + ': </strong>' + message.data.text + ' (' + message.data.date + ')' + '</p>'));
                    $('.last_message[data-uid='+uid+']').html(message.data.text);
                }
            }

        };

        sock.onclose = function () {
            console.log('close');
        };

        //send message
        $('form').on('submit', function(e){
            e.preventDefault();
            var text = $(this).find('textarea').val();
            sock.send(JSON.stringify({
                type: 'message',
                text: text
            }));
        });

        //select chat
        $('a.chat_selector').on('click', function(e){
            e.preventDefault();
            var uid = $(this).attr('data-uid');
            $('.chat_window').addClass('hide');
            $('.chat_window[data-uid='+uid+']').removeClass('hide');

            sock.send(JSON.stringify({
                type: "connect",
                chat: uid
            }));
        })

    </script>
{% endblock %}

templates/old/index.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <h2>{% trans 'Login' %}</h2>
    <p class="error"></p>
    {% if user.is_authenticated %}
        <p>{% trans 'Hello' %}, {{ user.username }}</p>
    {% endif %}
    <form action="{% url 'account:login' %}">{% csrf_token %}
        <input type="text" name="username" placeholder="{% trans 'Username' %}"/>
        <input type="password" name="password" placeholder="{% trans 'Password' %}"/>
        <input type="submit" value="{% trans 'Login' %}"/>
    </form>

    <p><a href="{% url 'chat:root' %}">{% trans 'Chat' %}</a></p>

{% endblock %}

{% block extra_js %}
    <script type="application/javascript">
        $('form').on('submit', function(e){
            e.preventDefault();
            var url = $(this).attr('action');
            var data = $(this).serializeArray();
            $.post(url, data, function(resp){
                console.log(resp);
                if (resp.success) {
                    location.reload();
                } else {
                    $('p.error').html(resp.error);
                }

            })
        })
    </script>
{% endblock %}